version: '3.7'

services:
  loanster_db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    networks:
      - network

  backend:
    build:
      context: . # Set the build context to the root of your project
      dockerfile: backend/Dockerfile.backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app/backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data: