version: '3.7'

services:
  loanster_db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - network

  backend:
    build:
      context: . # Set the build context to the root of your project
      dockerfile: backend/Dockerfile.backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: loanster_db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - ./backend:/app/backend
      - ./chain:/app/chain
      - ./unilib:/app/unilib
      - ./webapp:/app/webapp
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - network
    depends_on:
      - loanster_db

networks:
  network:
    driver: bridge

volumes:
  postgres-data: