# Use the official Node.js 18 image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy code to the container
COPY backend /app/backend

# Change the working directory to the backend folder
WORKDIR /app/backend

# Install the dependencies
RUN npm ci

# Expose the port the backend will run on
EXPOSE 3030

# Start the backend
CMD ["npm", "run", "start:dev"]
